package manifest

import (
	"os"
	"path/filepath"
	"sort"
	"testing"
)

// Real yarn v1 lockfile shape, copy-shaped from a small repro project.
const yarnV1Fixture = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@types/node@20.10.0":
  version "20.10.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.10.0.tgz#abc"
  integrity sha512-aaa

"@babel/core@^7.0.0":
  version "7.24.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz#xyz"
  integrity sha512-bbb
  dependencies:
    "@babel/parser" "^7.24.0"

express@^4.18.0, express@~4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz#qqq"
  integrity sha512-ccc

lodash@4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#zzz"
  integrity sha512-ddd

# This is a comment we should ignore
react@18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#aaa"
  integrity sha512-eee
`

func writeYarnLock(t *testing.T, dir, contents string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, "yarn.lock"), []byte(contents), 0o644); err != nil {
		t.Fatalf("write yarn.lock: %v", err)
	}
}

func TestParseYarnLockfile(t *testing.T) {
	dir := t.TempDir()
	writeYarnLock(t, dir, yarnV1Fixture)

	p := NewParser(dir)
	if !p.HasYarnLockfile() {
		t.Fatal("HasYarnLockfile=false, want true")
	}

	pkgs, err := p.ParseYarnLockfile()
	if err != nil {
		t.Fatalf("ParseYarnLockfile: %v", err)
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].Name < pkgs[j].Name })

	want := []Package{
		{Name: "@babel/core", Version: "7.24.0", Ecosystem: "npm"},
		{Name: "@types/node", Version: "20.10.0", Ecosystem: "npm"},
		{Name: "express", Version: "4.18.2", Ecosystem: "npm"},
		{Name: "lodash", Version: "4.17.21", Ecosystem: "npm"},
		{Name: "react", Version: "18.2.0", Ecosystem: "npm"},
	}
	if len(pkgs) != len(want) {
		t.Fatalf("got %d packages, want %d: %+v", len(pkgs), len(want), pkgs)
	}
	for i, p := range pkgs {
		if p != want[i] {
			t.Errorf("pkg[%d] = %+v, want %+v", i, p, want[i])
		}
	}
}

func TestParseYarnLockfile_MissingFile(t *testing.T) {
	p := NewParser(t.TempDir())
	pkgs, err := p.ParseYarnLockfile()
	if err != nil {
		t.Errorf("missing file should not error: %v", err)
	}
	if pkgs != nil {
		t.Errorf("expected nil, got %v", pkgs)
	}
}

// Multiple specs sharing one resolved version (the `, `-separated header
// case) must only emit ONE package entry — they're aliases for the same
// resolved version.
func TestParseYarnLockfile_DeduplicatesAliasedSpecs(t *testing.T) {
	dir := t.TempDir()
	writeYarnLock(t, dir, `express@^4.18.0, express@~4.18.0, express@4.x:
  version "4.18.2"
`)
	p := NewParser(dir)
	pkgs, _ := p.ParseYarnLockfile()
	if len(pkgs) != 1 || pkgs[0].Name != "express" || pkgs[0].Version != "4.18.2" {
		t.Errorf("expected single express@4.18.2, got %+v", pkgs)
	}
}

func TestPackageNameFromYarnSpec(t *testing.T) {
	cases := []struct{ in, want string }{
		{"lodash@^4.17.21", "lodash"},
		{"lodash@4.17.21", "lodash"},
		{"@types/node@20.10.0", "@types/node"},
		{"@types/node@^20.10.0", "@types/node"},
		{"@scope/pkg@1.0.0-beta.1", "@scope/pkg"},
		{"", ""},
		{"@only-scope", ""}, // no version separator
		{"no-at-symbol", ""},
	}
	for _, tc := range cases {
		got := packageNameFromYarnSpec(tc.in)
		if got != tc.want {
			t.Errorf("packageNameFromYarnSpec(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestVersionFromYarnLine(t *testing.T) {
	cases := []struct {
		in     string
		want   string
		wantOk bool
	}{
		{`version "4.17.21"`, "4.17.21", true},
		{`version 4.17.21`, "4.17.21", true}, // Berry sometimes omits quotes
		{`resolved "..."`, "", false},
		{`dependencies:`, "", false},
		{``, "", false},
	}
	for _, tc := range cases {
		got, ok := versionFromYarnLine(tc.in)
		if got != tc.want || ok != tc.wantOk {
			t.Errorf("versionFromYarnLine(%q) = (%q, %v), want (%q, %v)",
				tc.in, got, ok, tc.want, tc.wantOk)
		}
	}
}
